<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Keshav-Surface" failures="4" tests="6" name="Test" time="376.187" errors="0" timestamp="2023-08-03T19:06:05 IST">
  <testcase classname="com.testsuite.TestOne" name="UserAccessCreation on Thread[Thread-1,5,main]" time="123.43">
    <failure type="java.lang.AssertionError" message="Element By.xpath: //button[@class=&amp;apos;L0Z3Pu&amp;apos;] was not displayed in time - 60 Seconds - TimeoutException">
      <![CDATA[java.lang.AssertionError: Element By.xpath: //button[@class='L0Z3Pu'] was not displayed in time - 60 Seconds - TimeoutException
at com.selenium.Sync.waitUntilClickable(Sync.java:108)
at com.selenium.SafeActions.safeClick(SafeActions.java:58)
at com.page.module.flipkart.searchItem(flipkart.java:38)
at com.testsuite.TestOne.UserAccessCreation(TestOne.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- UserAccessCreation on Thread[Thread-1,5,main] -->
  <testcase classname="com.testsuite.TestOne" name="UserAccessCreation on Thread[Thread-1,5,main]" time="10.756"/>
  <testcase classname="com.testsuite.TestOne" name="UserAccessCreation on Thread[Thread-1,5,main]" time="8.668"/>
  <testcase classname="com.testsuite.TestOne" name="UserAccessCreation on Thread[Thread-1,5,main]" time="79.738">
    <failure type="java.lang.AssertionError" message="Unable to enter  in field By.xpath: //input[@id=&amp;apos;email&amp;apos;] in time - 60 Seconds">
      <![CDATA[java.lang.AssertionError: Unable to enter  in field By.xpath: //input[@id='email'] in time - 60 Seconds
at com.selenium.SafeActions.safeType(SafeActions.java:138)
at com.page.module.Persistant.EnterCredentials(Persistant.java:26)
at com.testsuite.TestOne.UserAccessCreation(TestOne.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- UserAccessCreation on Thread[Thread-1,5,main] -->
  <testcase classname="com.testsuite.TestOne" name="UserAccessCreation on Thread[Thread-1,5,main]" time="70.862">
    <failure type="java.lang.AssertionError" message="Unable to enter  in field By.xpath: //input[@id=&amp;apos;email&amp;apos;] in time - 60 Seconds">
      <![CDATA[java.lang.AssertionError: Unable to enter  in field By.xpath: //input[@id='email'] in time - 60 Seconds
at com.selenium.SafeActions.safeType(SafeActions.java:138)
at com.page.module.TechM.EnterCredentials(TechM.java:26)
at com.testsuite.TestOne.UserAccessCreation(TestOne.java:66)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- UserAccessCreation on Thread[Thread-1,5,main] -->
  <testcase classname="com.testsuite.TestOne" name="UserAccessCreation on Thread[Thread-1,5,main]" time="71.062">
    <failure type="java.lang.AssertionError" message="Unable to enter  in field By.xpath: //input[@id=&amp;apos;email&amp;apos;] in time - 60 Seconds">
      <![CDATA[java.lang.AssertionError: Unable to enter  in field By.xpath: //input[@id='email'] in time - 60 Seconds
at com.selenium.SafeActions.safeType(SafeActions.java:138)
at com.page.module.Wipro.EnterCredentials(Wipro.java:26)
at com.testsuite.TestOne.UserAccessCreation(TestOne.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- UserAccessCreation on Thread[Thread-1,5,main] -->
</testsuite> <!-- Test -->
