<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="0" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-26T18:49:17 IST" name="Default suite" finished-at="2023-07-26T18:49:36 IST" duration-ms="18981">
    <groups>
    </groups>
    <test started-at="2023-07-26T18:49:17 IST" name="Default test" finished-at="2023-07-26T18:49:36 IST" duration-ms="18981">
      <class name="com.testsuite.TestOne">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:Thread[Thread-0,5,main]]" started-at="2023-07-26T18:49:13 IST" name="beforeSuite" finished-at="2023-07-26T18:49:17 IST" duration-ms="4086" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="initializeBaseSetup(org.testng.ITestContext)[pri:0, instance:Thread[Thread-0,5,main]]" started-at="2023-07-26T18:49:17 IST" name="initializeBaseSetup" finished-at="2023-07-26T18:49:19 IST" duration-ms="2023" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@78b612c6]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeBaseSetup -->
        <test-method signature="UserAccessCreation(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Thread[Thread-0,5,main]]" started-at="2023-07-26T18:49:19 IST" name="UserAccessCreation" data-provider="UserAccess" finished-at="2023-07-26T18:49:24 IST" duration-ms="4638" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[flipkart]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Element By.xpath: //div[@class='FPdoLc lJ9FBc']//input[@value='Google Search'] was not found on the web page]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Element By.xpath: //div[@class='FPdoLc lJ9FBc']//input[@value='Google Search'] was not found on the web page
at org.testng.Assert.fail(Assert.java:111)
at com.selenium.SafeActions.safeClick(SafeActions.java:80)
at com.page.module.HomePage.searchPage(HomePage.java:27)
at com.testsuite.TestOne.UserAccessCreation(TestOne.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UserAccessCreation -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:Thread[Thread-0,5,main]]" started-at="2023-07-26T18:49:24 IST" name="getResult" finished-at="2023-07-26T18:49:24 IST" duration-ms="351" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=UserAccessCreation on Thread[Thread-0,5,main] status=FAILURE method=TestOne.UserAccessCreation(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Thread[Thread-0,5,main]] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="initializeBaseSetup(org.testng.ITestContext)[pri:0, instance:Thread[Thread-0,5,main]]" started-at="2023-07-26T18:49:24 IST" name="initializeBaseSetup" finished-at="2023-07-26T18:49:25 IST" duration-ms="980" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@78b612c6]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeBaseSetup -->
        <test-method signature="UserAccessCreation(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Thread[Thread-0,5,main]]" started-at="2023-07-26T18:49:25 IST" name="UserAccessCreation" data-provider="UserAccess" finished-at="2023-07-26T18:49:30 IST" duration-ms="4542" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[gmail]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Element By.xpath: //div[@class='FPdoLc lJ9FBc']//input[@value='Google Search'] was not found on the web page]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Element By.xpath: //div[@class='FPdoLc lJ9FBc']//input[@value='Google Search'] was not found on the web page
at org.testng.Assert.fail(Assert.java:111)
at com.selenium.SafeActions.safeClick(SafeActions.java:80)
at com.page.module.HomePage.searchPage(HomePage.java:27)
at com.testsuite.TestOne.UserAccessCreation(TestOne.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UserAccessCreation -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:Thread[Thread-0,5,main]]" started-at="2023-07-26T18:49:30 IST" name="getResult" finished-at="2023-07-26T18:49:30 IST" duration-ms="194" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=UserAccessCreation on Thread[Thread-0,5,main] status=FAILURE method=TestOne.UserAccessCreation(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Thread[Thread-0,5,main]] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="initializeBaseSetup(org.testng.ITestContext)[pri:0, instance:Thread[Thread-0,5,main]]" started-at="2023-07-26T18:49:30 IST" name="initializeBaseSetup" finished-at="2023-07-26T18:49:31 IST" duration-ms="926" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@78b612c6]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeBaseSetup -->
        <test-method signature="UserAccessCreation(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Thread[Thread-0,5,main]]" started-at="2023-07-26T18:49:31 IST" name="UserAccessCreation" data-provider="UserAccess" finished-at="2023-07-26T18:49:36 IST" duration-ms="4864" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[facebook]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Element By.xpath: //div[@class='FPdoLc lJ9FBc']//input[@value='Google Search'] was not found on the web page]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Element By.xpath: //div[@class='FPdoLc lJ9FBc']//input[@value='Google Search'] was not found on the web page
at org.testng.Assert.fail(Assert.java:111)
at com.selenium.SafeActions.safeClick(SafeActions.java:80)
at com.page.module.HomePage.searchPage(HomePage.java:27)
at com.testsuite.TestOne.UserAccessCreation(TestOne.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UserAccessCreation -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:Thread[Thread-0,5,main]]" started-at="2023-07-26T18:49:36 IST" name="getResult" finished-at="2023-07-26T18:49:36 IST" duration-ms="226" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=UserAccessCreation on Thread[Thread-0,5,main] status=FAILURE method=TestOne.UserAccessCreation(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Thread[Thread-0,5,main]] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
      </class> <!-- com.testsuite.TestOne -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
