<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="2" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-03T18:59:48 IST" name="Suite" finished-at="2023-08-03T19:06:05 IST" duration-ms="376187">
    <groups>
    </groups>
    <test started-at="2023-08-03T18:59:48 IST" name="Test" finished-at="2023-08-03T19:06:05 IST" duration-ms="376187">
      <class name="com.testsuite.TestOne">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:Thread[Thread-1,5,main]]" started-at="2023-08-03T18:59:44 IST" name="beforeSuite" finished-at="2023-08-03T18:59:48 IST" duration-ms="4057" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="initializeBaseSetup(org.testng.ITestContext)[pri:0, instance:Thread[Thread-1,5,main]]" started-at="2023-08-03T18:59:49 IST" name="initializeBaseSetup" finished-at="2023-08-03T18:59:51 IST" duration-ms="1390" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@7e1953f7]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeBaseSetup -->
        <test-method signature="UserAccessCreation(java.lang.reflect.Method,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Thread[Thread-1,5,main]]" started-at="2023-08-03T18:59:51 IST" name="UserAccessCreation" data-provider="UserAccess" finished-at="2023-08-03T19:01:54 IST" duration-ms="123430" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.testsuite.TestOne.UserAccessCreation(java.lang.reflect.Method,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Exception]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[flipart]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[keshav]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[keshav]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[flipkart]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Element By.xpath: //button[@class='L0Z3Pu'] was not displayed in time - 60 Seconds - TimeoutException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Element By.xpath: //button[@class='L0Z3Pu'] was not displayed in time - 60 Seconds - TimeoutException
at org.testng.Assert.fail(Assert.java:111)
at com.selenium.Sync.waitUntilClickable(Sync.java:108)
at com.selenium.SafeActions.safeClick(SafeActions.java:58)
at com.page.module.flipkart.searchItem(flipkart.java:38)
at com.testsuite.TestOne.UserAccessCreation(TestOne.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UserAccessCreation -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:Thread[Thread-1,5,main]]" started-at="2023-08-03T19:01:55 IST" name="getResult" finished-at="2023-08-03T19:01:55 IST" duration-ms="243" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=UserAccessCreation on Thread[Thread-1,5,main] status=FAILURE method=TestOne.UserAccessCreation(java.lang.reflect.Method,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Thread[Thread-1,5,main]] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="initializeBaseSetup(org.testng.ITestContext)[pri:0, instance:Thread[Thread-1,5,main]]" started-at="2023-08-03T19:01:55 IST" name="initializeBaseSetup" finished-at="2023-08-03T19:01:56 IST" duration-ms="639" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@7e1953f7]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeBaseSetup -->
        <test-method signature="UserAccessCreation(java.lang.reflect.Method,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Thread[Thread-1,5,main]]" started-at="2023-08-03T19:01:56 IST" name="UserAccessCreation" data-provider="UserAccess" finished-at="2023-08-03T19:02:06 IST" duration-ms="10756" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.testsuite.TestOne.UserAccessCreation(java.lang.reflect.Method,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Exception]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[gmail]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[keshav]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[keshav]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[gmail]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UserAccessCreation -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:Thread[Thread-1,5,main]]" started-at="2023-08-03T19:02:06 IST" name="getResult" finished-at="2023-08-03T19:02:07 IST" duration-ms="208" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=UserAccessCreation on Thread[Thread-1,5,main] status=SUCCESS method=TestOne.UserAccessCreation(java.lang.reflect.Method,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Thread[Thread-1,5,main]] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="initializeBaseSetup(org.testng.ITestContext)[pri:0, instance:Thread[Thread-1,5,main]]" started-at="2023-08-03T19:02:07 IST" name="initializeBaseSetup" finished-at="2023-08-03T19:02:07 IST" duration-ms="630" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@7e1953f7]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeBaseSetup -->
        <test-method signature="UserAccessCreation(java.lang.reflect.Method,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Thread[Thread-1,5,main]]" started-at="2023-08-03T19:02:07 IST" name="UserAccessCreation" data-provider="UserAccess" finished-at="2023-08-03T19:02:16 IST" duration-ms="8668" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.testsuite.TestOne.UserAccessCreation(java.lang.reflect.Method,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Exception]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[facebook]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[keshav]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[keshav]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[facebook]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UserAccessCreation -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:Thread[Thread-1,5,main]]" started-at="2023-08-03T19:02:16 IST" name="getResult" finished-at="2023-08-03T19:02:16 IST" duration-ms="408" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=UserAccessCreation on Thread[Thread-1,5,main] status=SUCCESS method=TestOne.UserAccessCreation(java.lang.reflect.Method,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Thread[Thread-1,5,main]] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="initializeBaseSetup(org.testng.ITestContext)[pri:0, instance:Thread[Thread-1,5,main]]" started-at="2023-08-03T19:02:16 IST" name="initializeBaseSetup" finished-at="2023-08-03T19:02:18 IST" duration-ms="1796" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@7e1953f7]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeBaseSetup -->
        <test-method signature="UserAccessCreation(java.lang.reflect.Method,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Thread[Thread-1,5,main]]" started-at="2023-08-03T19:02:18 IST" name="UserAccessCreation" data-provider="UserAccess" finished-at="2023-08-03T19:03:38 IST" duration-ms="79738" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.testsuite.TestOne.UserAccessCreation(java.lang.reflect.Method,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Exception]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[persistent systems]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[persistent systems]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to enter  in field By.xpath: //input[@id='email'] in time - 60 Seconds]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to enter  in field By.xpath: //input[@id='email'] in time - 60 Seconds
at org.testng.Assert.fail(Assert.java:111)
at com.selenium.SafeActions.safeType(SafeActions.java:138)
at com.page.module.Persistant.EnterCredentials(Persistant.java:26)
at com.testsuite.TestOne.UserAccessCreation(TestOne.java:63)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UserAccessCreation -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:Thread[Thread-1,5,main]]" started-at="2023-08-03T19:03:39 IST" name="getResult" finished-at="2023-08-03T19:03:39 IST" duration-ms="219" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=UserAccessCreation on Thread[Thread-1,5,main] status=FAILURE method=TestOne.UserAccessCreation(java.lang.reflect.Method,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Thread[Thread-1,5,main]] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="initializeBaseSetup(org.testng.ITestContext)[pri:0, instance:Thread[Thread-1,5,main]]" started-at="2023-08-03T19:03:39 IST" name="initializeBaseSetup" finished-at="2023-08-03T19:03:40 IST" duration-ms="695" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@7e1953f7]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeBaseSetup -->
        <test-method signature="UserAccessCreation(java.lang.reflect.Method,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Thread[Thread-1,5,main]]" started-at="2023-08-03T19:03:40 IST" name="UserAccessCreation" data-provider="UserAccess" finished-at="2023-08-03T19:04:51 IST" duration-ms="70862" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.testsuite.TestOne.UserAccessCreation(java.lang.reflect.Method,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Exception]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[tech mahindra]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[tech mahindra]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to enter  in field By.xpath: //input[@id='email'] in time - 60 Seconds]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to enter  in field By.xpath: //input[@id='email'] in time - 60 Seconds
at org.testng.Assert.fail(Assert.java:111)
at com.selenium.SafeActions.safeType(SafeActions.java:138)
at com.page.module.TechM.EnterCredentials(TechM.java:26)
at com.testsuite.TestOne.UserAccessCreation(TestOne.java:66)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UserAccessCreation -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:Thread[Thread-1,5,main]]" started-at="2023-08-03T19:04:52 IST" name="getResult" finished-at="2023-08-03T19:04:52 IST" duration-ms="195" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=UserAccessCreation on Thread[Thread-1,5,main] status=FAILURE method=TestOne.UserAccessCreation(java.lang.reflect.Method,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Thread[Thread-1,5,main]] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="initializeBaseSetup(org.testng.ITestContext)[pri:0, instance:Thread[Thread-1,5,main]]" started-at="2023-08-03T19:04:52 IST" name="initializeBaseSetup" finished-at="2023-08-03T19:04:53 IST" duration-ms="687" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@7e1953f7]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeBaseSetup -->
        <test-method signature="UserAccessCreation(java.lang.reflect.Method,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Thread[Thread-1,5,main]]" started-at="2023-08-03T19:04:53 IST" name="UserAccessCreation" data-provider="UserAccess" finished-at="2023-08-03T19:06:04 IST" duration-ms="71062" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.testsuite.TestOne.UserAccessCreation(java.lang.reflect.Method,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Exception]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[wipro]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[wipro]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to enter  in field By.xpath: //input[@id='email'] in time - 60 Seconds]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to enter  in field By.xpath: //input[@id='email'] in time - 60 Seconds
at org.testng.Assert.fail(Assert.java:111)
at com.selenium.SafeActions.safeType(SafeActions.java:138)
at com.page.module.Wipro.EnterCredentials(Wipro.java:26)
at com.testsuite.TestOne.UserAccessCreation(TestOne.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UserAccessCreation -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:Thread[Thread-1,5,main]]" started-at="2023-08-03T19:06:04 IST" name="getResult" finished-at="2023-08-03T19:06:05 IST" duration-ms="211" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=UserAccessCreation on Thread[Thread-1,5,main] status=FAILURE method=TestOne.UserAccessCreation(java.lang.reflect.Method,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Thread[Thread-1,5,main]] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
      </class> <!-- com.testsuite.TestOne -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
